import PDFDocument from "pdfkit";

const stripHtml = (html) => {
  if (!html) return "";
  return html
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
};

/**
 * Automatically generates a professional PDF buffer for email attachments.
 *
 * @param {Object} options
 * @param {string} options.to - Recipient email address
 * @param {string} options.subject - Email subject
 * @param {string} [options.text] - Plain text body
 * @param {string} [options.html] - HTML body
 * @param {string} [options.pdfTitle] - Optional custom title for the PDF header
 * @param {string} [options.pdfContent] - Optional custom content body for the PDF
 * @returns {Promise<Buffer>}
 */
export const generateEmailPdf = ({
  to,
  subject = "Notification",
  text,
  html,
  pdfTitle,
  pdfContent,
}) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      const buffers = [];
      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (error) => reject(error));

      // Header Banner
      doc
        .rect(50, 45, 495, 45)
        .fill("#2563eb");

      doc
        .fillColor("#ffffff")
        .fontSize(18)
        .font("Helvetica-Bold")
        .text(pdfTitle || "CONFIRMATION & DELIVERY RECORD", 65, 58);

      doc.moveDown(3);

      // Metadata Card
      doc
        .rect(50, 110, 495, 90)
        .fillAndStroke("#f8fafc", "#e2e8f0");

      doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(11);
      doc.text("Recipient:", 65, 125);
      doc.font("Helvetica").text(to, 140, 125);

      doc.font("Helvetica-Bold").text("Subject:", 65, 145);
      doc.font("Helvetica").text(subject, 140, 145);

      doc.font("Helvetica-Bold").text("Generated:", 65, 165);
      doc.font("Helvetica").text(new Date().toUTCString(), 140, 165);

      // Body Section
      doc.moveDown(5);
      doc.fillColor("#334155").font("Helvetica-Bold").fontSize(14);
      doc.text("Message Details", 50, 220);

      doc
        .moveTo(50, 240)
        .lineTo(545, 240)
        .strokeColor("#cbd5e1")
        .stroke();

      const bodyText =
        pdfContent ||
        text ||
        stripHtml(html) ||
        "This document confirms that your email was processed and dispatched successfully.";

      doc
        .fillColor("#475569")
        .font("Helvetica")
        .fontSize(11)
        .text(bodyText, 50, 255, {
          width: 495,
          lineGap: 4,
        });

      // Footer
      doc
        .fontSize(9)
        .fillColor("#94a3b8")
        .text(
          "Automated Document Attachment • Generated by nodemailer-email-sender",
          50,
          750,
          { align: "center", width: 495 }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
